import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#19120a',
        'secondary-container': '#533294',
        'tertiary': '#9bd9ff',
        'on-background': '#eee0d2',
        'tertiary-fixed': '#c4e7ff',
        'outline-variant': '#524534',
        'background': '#19120a',
        'primary-container': '#f5a623',
        'secondary-fixed': '#eaddff',
        'secondary-fixed-dim': '#d2bcff',
        'primary-fixed-dim': '#ffb955',
        'on-tertiary-container': '#004d6a',
        'on-secondary': '#3c167c',
        'error': '#ffb4ab',
        'tertiary-fixed-dim': '#7cd0ff',
        'on-secondary-fixed-variant': '#533294',
        'on-primary-fixed-variant': '#633f00',
        'outline': '#9f8e7a',
        'tertiary-container': '#3ac2ff',
        'surface-container-lowest': '#130d06',
        'surface-bright': '#40382e',
        'on-secondary-fixed': '#25005a',
        'surface-container-low': '#211a12',
        'inverse-surface': '#eee0d2',
        'on-error': '#690005',
        'error-container': '#93000a',
        'surface-tint': '#ffb955',
        'surface': '#19120a',
        'on-error-container': '#ffdad6',
        'surface-container': '#251e16',
        'on-primary-fixed': '#291800',
        'on-primary': '#452b00',
        'on-surface': '#eee0d2',
        'on-tertiary-fixed-variant': '#004c69',
        'secondary': '#d2bcff',
        'on-tertiary': '#00344a',
        'inverse-on-surface': '#372f26',
        'surface-container-high': '#302920',
        'on-primary-container': '#644000',
        'on-surface-variant': '#d7c3ae',
        'on-secondary-container': '#c3a6ff',
        'primary-fixed': '#ffddb4',
        'primary': '#ffc880',
        'surface-variant': '#3c332a',
        'on-tertiary-fixed': '#001e2c',
        'inverse-primary': '#835500',
        'surface-container-highest': '#3c332a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': 'auto',
        'sm': '16px',
        'lg': '40px',
        'margin-mobile': '20px',
        'xl': '64px',
        'gutter': '16px',
        'base': '4px',
        'md': '24px',
        'xs': '8px',
      },
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit'],
        'label-sm': ['Outfit'],
        'body-lg': ['Outfit'],
        'headline-lg-mobile': ['Outfit'],
        'label-md': ['Outfit'],
        'display-lg': ['Outfit'],
        'body-md': ['Outfit'],
        'headline-lg': ['Outfit'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

export default config
